MyFirstASPNETWebApp/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstASPNETWebApp.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FanMail ()
        {
            return View();
        }
    }
}

MyFirstASPNETWebApp/Views/Blah/FanMail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Fan Mail";
}

<h2>Send Him Fan Mail</h2>
<form>
    <label>From:</label>
    <input id="txtFrom" /> <br />
    <label>Subject:</label>
    <input id="txtSubject" /> <br />
    <label>Message:</label>
    <textarea id="txtMessage" rows="4"></textarea>
    <br />
    <input id="btnSend" type="button" value="Send Message" />
</form>

<script src="js/FanMail.js"></script>

MyFirstASPNETWebApp/Views/Blah/index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Prof. Ganderson Fan Club";
}

<h1>Prof. Ganderson Fan Site</h1>
<img id="picGanderson" src="img/profganderson.jpeg" />
<p> Prof. Anderson (a.k.a. "Prof. Ganderson") is a Professor in the Information Systems department at BYU</p>
<p>Pop Quiz: We love him because:</p>
<ul>
    <li>A: The flowing locks he had when he was younger</li>
    <li>B: He can pound a pound of bacon</li>
    <li>C: His exams are so easy</li>
    <li>D: He is just an awesome person who cares about everybody around him</li>
    <li>E: All of the above</li>
</ul>

MyFirstASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/css/default.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="FanMail">Fan Mail</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer>This is the footer.</footer>

    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.0.min.js"></script>
</body>

</html>